server:
  port: 8084

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5436/subscriptiondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update  # ✅ enables auto table creation in dev
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  jackson:
    date-format: dd MMM, yyyy HH:mm z
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

product:
  service:
    base-url: http://54.238.204.246:8080  # Replace with actual URL if needed

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    aforo.subscriptionservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

aforo:
  jwt:
    issuer: aforo-billablemetrics
    secret: ${JWT_SECRET:change-me-please-change-me-32-bytes-min}  # env var or fallback
    expiryMinutes: 120
  cors:
    # Comma-separated list; used by SecurityConfig.corsConfigurationSource()
    # Include your frontend origin(s). Add https variants if applicable.
    allowed-origins: "http://13.115.248.133,http://localhost:3000"
    allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type,X-Organization-Id"
    allow-credentials: true
