package aforo.subscriptionservice.dto;

import java.util.UUID;

import aforo.subscriptionservice.entity.PaymentType;
import aforo.subscriptionservice.entity.SubscriptionStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

import java.time.Instant;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SubscriptionResponse {

    private Long subscriptionId;
    private Long customerId; // Changed from Integer to UUID
    private Long productId;
    private Long ratePlanId;
    private SubscriptionStatus status;
    private Instant createdOn;
    private Instant lastUpdated;
    private PaymentType paymentType;

    private String adminNotes;
    
    // Enriched fields from external services
    // customerName is excluded when null to hide it in responses where we can't fetch it (circular dependency prevention)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String customerName;
    private String productName;
    private String icon;
    private String ratePlanName;
    private String ratePlanType;
    
    private Long organizationId;

    // Billing cycle fields
    private Instant currentBillingPeriodStart;
    private Instant currentBillingPeriodEnd;
    private Instant nextBillingTimestamp;
    private String billingAnchorInfo;
    private Boolean autoRenew;
    private String billingFrequency;  // Enriched from rate plan
    
    // Billable metrics fields
    private String billableUid;
    private String usageCondition;
    private String unitOfMeasure;
    private String billingCriteria;
    
    // Additional setters for fields that might not be generated by Lombok
    public void setRatePlanType(String ratePlanType) {
        this.ratePlanType = ratePlanType;
    }
    
    public void setBillableUid(String billableUid) {
        this.billableUid = billableUid;
    }
    
    public void setUsageCondition(String usageCondition) {
        this.usageCondition = usageCondition;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    
    public void setRatePlanName(String ratePlanName) {
        this.ratePlanName = ratePlanName;
    }
    
    public void setBillingFrequency(String billingFrequency) {
        this.billingFrequency = billingFrequency;
    }
    
    public void setBillingCriteria(String billingCriteria) {
        this.billingCriteria = billingCriteria;
    }
    
    public void setUnitOfMeasure(String unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
}
